### PR TITLE
Suggests DNF5 installation on 38+ again

### PR DESCRIPTION
**Pull request by praiskup**
Actually, having DNF5 on Fedora 38 Mock **host** is still a good idea for the future when we'll be building Fedora 41 chroots.

This reverts commit 8cca2d02aef81c8dbfb05ba46bb2e8bdf37baafb.

### CODE REVIEW

**Comment by praiskup** [comment]
FYI @evan-goode @j-mracek  - mostly related to our today discussion that we should proopose building of Fedora 41 chroots with dnf5 rather soon.

**Comment by Conan-Kudo** [comment]
Suggests doesn't do anything. You need to use Recommends instead if you want it to actually get installed.

**Comment by praiskup** [comment]
With the bootstrap image feature ON by default, it really isn't worth more than just Suggests?

**Comment by Conan-Kudo** [comment]
We don't have it on by default universally.

**Comment by praiskup** [comment]
That's true, the question is what to do about it.  Do you have a proposal? :)

My understanding is that users have to decide whether they prefer (a) bootstrap image, (b) any package manager (that is actually able to install bootstrap, aka bootstrap image off) or (c) a particular package manager version on the host.  Pushing DNF5 installation on user's hosts doesn't seem **so necessary** considering that we already [kinda push for (a)](https://github.com/rpm-software-management/mock/pull/1101).  The image feature needs to settle down, but long term it is going to be the generally preferred variant, I believe.

**Comment by Conan-Kudo** [comment]
I think we should use Recommends for the package managers. If they don't want it, they can uninstall it and it won't come back again.

**Review by Conan-Kudo — APPROVED** [review]

**Review by xsuchy — APPROVED** [review]

**Comment by decathorpe** [comment]
Meh, this is really annoying. I'll need to add `exclude=dnf5,yum` to my dnf configuration because of this.

**Comment by j-mracek** [comment]
> Meh, this is really annoying. I'll need to add `exclude=dnf5,yum` to my dnf configuration because of this.

May I ask you what kind of problem you have with `DNF5`? The problems we can resolve.

**Comment by decathorpe** [comment]
I don't have a problem with dnf5, but I don't like the kind of dependency bloat changes like these cause. I already have `exclude=podman,toolbox` in my dnf.conf, and now it's `exclude=podman,toolbox,dnf5,yum` ...

**Pull request merged**
