### PR TITLE
Add Circle Linux 9 configs

### PR DESCRIPTION
**Pull request by bella485**
Circle Linux 9.3 released, now support x86_64 aarch64 ppc64le s390x.

### CODE REVIEW

**Comment by bella485** [comment]
Hi man ～ I pushed patch for circlelinux to latest main branch.  please help me review and merge it , anything need to fix please tell me , thank  your effort ~

**Comment by praiskup** [comment]
Please provide release notes snippet, per the instructions
https://rpm-software-management.github.io/mock/Release-Notes-New-Entry

The `testing-farm` output shows that the circlelinux 9 fails:

```
FAILED: circlelinux-8-x86_64.cfg (tmpfs)
FAILED: circlelinux-8-x86_64.cfg
FAILED: circlelinux-9-x86_64.cfg (tmpfs)
FAILED: circlelinux-9-x86_64.cfg
FAILED: circlelinux+epel-8-x86_64.cfg (tmpfs)
FAILED: circlelinux+epel-8-x86_64.cfg
FAILED: circlelinux+epel-9-x86_64.cfg (tmpfs)
FAILED: circlelinux+epel-9-x8+ : 'The '\''make check'\'' testsuite passed.'
6_64.cfg
```

When I try locally, with `dnf copr enable copr.fedorainfracloud.org/@mock/mock-pull-requests:pr:1366`:
```
Start(bootstrap): chroot init
INFO: mounting tmpfs at /var/lib/mock/circlelinux-9-x86_64-bootstrap/root.
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start(bootstrap): cleaning package manager metadata
Finish(bootstrap): cleaning package manager metadata
INFO: Guessed host environment type: unknown
INFO: Using bootstrap image: quay.io/cclinux/circlelinux:9
INFO: Pulling image: quay.io/cclinux/circlelinux:9
INFO: Copy content of container quay.io/cclinux/circlelinux:9 to /var/lib/mock/circlelinux-9-x86_64-bootstrap/root
INFO: Checking that quay.io/cclinux/circlelinux:9 image matches host's architecture
INFO: mounting quay.io/cclinux/circlelinux:9 with podman image mount
INFO: image quay.io/cclinux/circlelinux:9 as /var/lib/containers/storage/overlay/4e1a369a4041f69e865308a1954fb12ad92a2d095fe8b295faed67384c6b6903/merged
INFO: umounting image quay.io/cclinux/circlelinux:9 (/var/lib/containers/storage/overlay/4e1a369a4041f69e865308a1954fb12ad92a2d095fe8b295faed67384c6b6903/merged) with podman image umount
INFO: Package manager dnf detected and used (fallback)
WARNING: Source contains parsing errors: '<string>'
        [line 149]: 'metadata_expireNFVh\n'
INFO: Bootstrap image not marked ready
Start(bootstrap): installing dnf tooling
Config error: Parsing file "/etc/dnf/dnf.conf" failed: Parsing file '/etc/dnf/dnf.conf' failed: IniParser: Missing '=' at line 149
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M c181d12125da47d69ed9ee9a971919f6 -D /var/lib/mock/circlelinux-9-x86_64-bootstrap/root -a --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/circlelinux-9-x86_64-bootstrap/root/installation-homedir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 --resolv-conf=off /usr/bin/dnf-3 --releasever 9 --setopt=deltarpm=False --setopt=allow_vendor_change=yes --allowerasing --disableplugin=local --disableplugin=spacewalk --disableplugin=versionlock install python3-dnf python3-dnf-plugins-core --setopt=tsflags=nocontexts
Config error: Parsing file "/etc/dnf/dnf.conf" failed: Parsing file '/etc/dnf/dnf.conf' failed: IniParser: Missing '=' at line 149
```

**Comment by bella485** [comment]
> release notes snippet

about release notes ， I'm not quite sure which file needs to be modified ？

**Comment by xsuchy** [comment]
See https://github.com/rpm-software-management/mock/blob/main/docs/Release-Notes-New-Entry.md

**Comment by bella485** [comment]
> See https://github.com/rpm-software-management/mock/blob/main/docs/Release-Notes-New-Entry.md

thanks a lot , now i get it. 

```
pip3 install towncrier
towncrier create add-circlelinux-9-mock-config.config  
// towncrier will create your file on path releng/release-notes-next/ , tips there are config\bugfix and other type.
vim releng/release-notes-next/add-circlelinux-9-mock-config.config
git add releng/release-notes-next/add-circlelinux-9-mock-config.config
git push 
```

**Comment by bella485** [comment]
> Please provide release notes snippet, per the instructions https://rpm-software-management.github.io/mock/Release-Notes-New-Entry
> 
> The `testing-farm` output shows that the circlelinux 9 fails:
> 
> ```
> FAILED: circlelinux-8-x86_64.cfg (tmpfs)
> FAILED: circlelinux-8-x86_64.cfg
> FAILED: circlelinux-9-x86_64.cfg (tmpfs)
> FAILED: circlelinux-9-x86_64.cfg
> FAILED: circlelinux+epel-8-x86_64.cfg (tmpfs)
> FAILED: circlelinux+epel-8-x86_64.cfg
> FAILED: circlelinux+epel-9-x86_64.cfg (tmpfs)
> FAILED: circlelinux+epel-9-x8+ : 'The '\''make check'\'' testsuite passed.'
> 6_64.cfg
> ```
> 
> When I try locally, with `dnf copr enable copr.fedorainfracloud.org/@mock/mock-pull-requests:pr:1366`:
> 
> ```
> Start(bootstrap): chroot init
> INFO: mounting tmpfs at /var/lib/mock/circlelinux-9-x86_64-bootstrap/root.
> INFO: calling preinit hooks
> INFO: enabled root cache
> INFO: enabled package manager cache
> Start(bootstrap): cleaning package manager metadata
> Finish(bootstrap): cleaning package manager metadata
> INFO: Guessed host environment type: unknown
> INFO: Using bootstrap image: quay.io/cclinux/circlelinux:9
> INFO: Pulling image: quay.io/cclinux/circlelinux:9
> INFO: Copy content of container quay.io/cclinux/circlelinux:9 to /var/lib/mock/circlelinux-9-x86_64-bootstrap/root
> INFO: Checking that quay.io/cclinux/circlelinux:9 image matches host's architecture
> INFO: mounting quay.io/cclinux/circlelinux:9 with podman image mount
> INFO: image quay.io/cclinux/circlelinux:9 as /var/lib/containers/storage/overlay/4e1a369a4041f69e865308a1954fb12ad92a2d095fe8b295faed67384c6b6903/merged
> INFO: umounting image quay.io/cclinux/circlelinux:9 (/var/lib/containers/storage/overlay/4e1a369a4041f69e865308a1954fb12ad92a2d095fe8b295faed67384c6b6903/merged) with podman image umount
> INFO: Package manager dnf detected and used (fallback)
> WARNING: Source contains parsing errors: '<string>'
>         [line 149]: 'metadata_expireNFVh\n'
> INFO: Bootstrap image not marked ready
> Start(bootstrap): installing dnf tooling
> Config error: Parsing file "/etc/dnf/dnf.conf" failed: Parsing file '/etc/dnf/dnf.conf' failed: IniParser: Missing '=' at line 149
> ERROR: Command failed: 
>  # /usr/bin/systemd-nspawn -q -M c181d12125da47d69ed9ee9a971919f6 -D /var/lib/mock/circlelinux-9-x86_64-bootstrap/root -a --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/circlelinux-9-x86_64-bootstrap/root/installation-homedir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 --resolv-conf=off /usr/bin/dnf-3 --releasever 9 --setopt=deltarpm=False --setopt=allow_vendor_change=yes --allowerasing --disableplugin=local --disableplugin=spacewalk --disableplugin=versionlock install python3-dnf python3-dnf-plugins-core --setopt=tsflags=nocontexts
> Config error: Parsing file "/etc/dnf/dnf.conf" failed: Parsing file '/etc/dnf/dnf.conf' failed: IniParser: Missing '=' at line 149
> ```

Hi man , added release notes and fix mock init error.  thank your effort again  !

**Review by praiskup — APPROVED** [review]
LGTM!

**Pull request merged**
