### PR TITLE
configs: branch F41

### PR DESCRIPTION
**Pull request by FrostyX**
Branching F41 configs from Rawhide using `releng/rawhide-branching.sh`.
Schedule: https://fedorapeople.org/groups/schedule/f-41/f-41-all-tasks.html

### CODE REVIEW

**Comment by FrostyX** [comment]
The configs don't work yet and still return 404 on the repositories. The branching is probably still in progress? We will see tomorrow.

**Comment by praiskup** [comment]
> *  FAILED: /tmp/tmp.E8nQA1Mgh0-mock-old-tests/mock/integration-tests/23-local-mirrorlist.tst

Seems like candidate for fixing, though we are not releasing new mock ATM. +1

**Comment by praiskup** [comment]
Hmm
```
FAILED: fedora-41-x86_64.cfg (tmpfs)
FAILED: fedora-41-x86_64.cfg
PASSED: fedora-42-i386.cfg (tmpfs)
PASSED: fedora-42-i386.cfg
FAILED: fedora-42-x86_64.cfg (tmpfs)
FAILED: fedora-42-x86_64.cfg
PASSED: fedora-eln-x86_64.cfg (tmpfs)
PASSED: fedora-eln-x86_64.cfg
PASSED: fedora-rawhide-i386.cfg (tmpfs)
PASSED: fedora-rawhide-i386.cfg
FAILED: fedora-rawhide-x86_64.cfg (tmpfs)
FAILED: fedora-rawhide-x86_64.cfg
```

**Comment by praiskup** [comment]
> cannot open file: (2) - No such file or directory [/usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-43-primary]

We need to bump the `distribution-gpg-keys` requirement to 1.105+.

**Comment by FrostyX** [comment]
> We need to bump the distribution-gpg-keys requirement to 1.105+.

Updated

**Comment by praiskup** [comment]
LGTM

**Pull request merged**
