### PR TITLE
bootstrap_image: podman run with seccomp=unconfined

### PR DESCRIPTION
**Pull request by praiskup**
Related: rhbz#2034209

### CODE REVIEW

**Comment by praiskup** [comment]
Note this PR is EL7 only, but we disabled seccomp for system-nspawn in 2f1e09c6d8cebb313ea9de12da29f735e30f907c so not sure....  should we do this for `main` branch, too?

**Comment by xsuchy** [comment]
I understand this is needed only on EL7 and only as temporary measurement. I do not see reason why this should be needed in main. Right?
For mock-2 +1

**Review by xsuchy — APPROVED** [review]

**Comment by praiskup** [comment]
> I do not see reason why this should be needed in main. Right?

These seccomp rules have bitten us many times before, so I think we'll have to do this sooner or later
in `main` too.

**Comment by praiskup** [comment]
Mirek: We should have a knob for turning on the seccomp (both for podman and systemd-nspawn)

**Comment by praiskup** [comment]
Moving to #885.

**Pull request closed without merging**
