### PR TITLE
mageia-cauldron: Change releasever to 7

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Mageia 6 is released and branched from Cauldron now.

### CODE REVIEW

**Comment by xsuchy** [comment]
so do we want mageia-7-* configs too?

**Comment by Conan-Kudo** [comment]
@xsuchy They don't exist yet...

**Comment by Conan-Kudo** [comment]
Since there's no Mageia 7 branch yet, there's nothing to point it to.

**Comment by Conan-Kudo** [comment]
@xsuchy Can we please have this pulled in? It's a trivial change...

**Comment by praiskup** [comment]
@Conan-Kudo, @xsuchy is now on vacation, afaik

**Pull request merged**
