### PR TITLE
Move to GH Actions

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by praiskup** [comment]
Packit needs to be enabled, but I don't seem to have rights... @xsuchy can you give the app access here?

But I'm afraid we can not configure more than one spec file, anyway.  @ttomecek?

**Comment by praiskup** [comment]
JFTR, @lachmanfrantisek confirmed it is not yet possible, more RPMs per one Git repo is on the TODO list (so still, it would be nice to have Packit enabled here).

**Comment by praiskup** [comment]
Packit issue: https://github.com/packit/packit/issues/397

**Comment by Conan-Kudo** [comment]
@praiskup Packit requires one spec == one repo. Our multi-package setup will not work.

**Comment by praiskup** [comment]
Does anyone want to take a look?

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
