### PR TITLE
config: add best=1 also into rawhide configs

### PR DESCRIPTION
**Pull request by praiskup**
Per discussion on fedora devel, and bug-report against Copr.
Complements 015f5771.

Version: 1.3.3-1

### CODE REVIEW

**Comment by xsuchy** [comment]
+1, but....

I plan to do release in one week. And I am really afraid that this change may break Koji builds. So I will merge it *after* the release. Give it 2 months in git, so it can be tested by people who use nightlies. And if everything will be fine, it will be part of 1.3.5.

**Comment by ignatenkobrain** [comment]
koji never has more than one version of package in buildroot

**Comment by xsuchy** [comment]
OK. Then lets break it :)

**Comment by xsuchy** [comment]
Merged.

**Comment by ausil** [comment]
I am not a fan of this change. however it will have zero impact on koji as koji generates its own mock configs on the fly. people may experience different behaviour between koji and mock. If they do we have to be prepared to revert this change

**Pull request closed without merging**
