### PR TITLE
openEuler 24.03 LTS

### PR DESCRIPTION
**Pull request by nuqleo**
Configs for openEuler 24.03 LTS based on

mock-core-configs/etc/mock/templates/openeuler-22.03.tpl
mock-core-configs/etc/mock/openeuler-22.03-aarch64.cfg
mock-core-configs/etc/mock/openeuler-22.03-x86_64.cfg

### CODE REVIEW

**Comment by pkking** [comment]
@nuqleo please fix the CI

**Comment by nuqleo** [comment]
Added changelog but don't understand what wrong now.

**Comment by pkking** [comment]
@FrostyX @praiskup anything suggestions appreciated!😀

**Comment by FrostyX** [comment]
> Added changelog but don't understand what wrong now.

There is a small bug in the regex for checking the presence of the changelog file.
It fails because of the dot in the version number. This fails `add-openeuler-24.03.config`, this should work `add-openeuler-2403.config`.

Can you please rename the file? And while doing so, can you please squash all of the commits together into one?

Other than that, everything looks good to me. I tried

```
mock --configdir /home/jkadlcik/git/mock/mock-core-configs/etc/mock/ -r openeuler-24.03-x86_64 --shell
mock --configdir /home/jkadlcik/git/mock/mock-core-configs/etc/mock/ -r openeuler-24.03-aarch64 --shell
```

and they work fine :-)

**Comment by pkking** [comment]
LGTM

**Review by FrostyX — APPROVED** [review]
Thank you very much for the changes.

**Pull request merged**
