### PR TITLE
Use non development bootstrap image for CentOS Stream 10

### PR DESCRIPTION
**Pull request by Romain-Geissler-1A**
cc @carlwgeorge Who did the last commit using the development image for CentOS 10 Streams.

### CODE REVIEW

**Comment by carlwgeorge** [comment]
Yup, I can confirm the regular `stream10` tag was added, see [this issue](https://issues.redhat.com/browse/CS-2618).

**Review by carlwgeorge — APPROVED** [review]

**Review by praiskup — APPROVED** [review]
Awesome, thank you!

**Comment by praiskup** [comment]
PASSED: centos-stream-10-x86_64.cfg (tmpfs)
PASSED: centos-stream-10-x86_64.cfg

**Comment by martinpitt** [comment]
@praiskup @Romain-Geissler-1A Please please revert this. The production compose lags behind weeks and months, see https://issues.redhat.com/browse/CS-2309 . I just tried to move our CentOS 10 image from devel to prod compose, and it's at least a 5 week step backwards. This will make packages build against outdated libraries/toolchains.

The CentOS 10 composes have been a mess since their inception, and this needs sorting out, see also the last comments on https://issues.redhat.com/browse/CS-2642 . But as of today this switch is still premature.

**Comment by carlwgeorge** [comment]
This should not be reverted.  Neither container image is pointing to the compose repos.  They have identical repo files which point to the mirror network, so they see the same packages for the purposes of mock.  Reverting this PR won't change what packages are visible.  Furthermore, for the examples given in the linked issues, the packages baked into the image are all either the same or newer in the `centos:stream10` image, so it's objectively better to keep using this image.

This is the correct tag to use going forward, as per https://issues.redhat.com/browse/CS-2618.  Any issues with the composes is orthogonal to this mock change.

**Comment by martinpitt** [comment]
> Neither container image is pointing to the compose repos. They

Assuming s/compose/devel/, ok -- so in effect this has always been outdated? Thanks.

**Comment by carlwgeorge** [comment]
Well, there are two composes, the development compose and the production compose.

- https://composes.stream.centos.org/stream-10/development/latest-CentOS-Stream/compose/
- https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/

The production composes are what gets pushed out to the main mirror and duplicated through the mirror network.

- https://mirror.stream.centos.org/10-stream/

Both the `centos:stream10-development` and `centos:stream10` images are both configured to use the mirror network and see the same packages.

**Pull request merged**
