### PR TITLE
configs: CentOS 7 is EOL

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by praiskup** [comment]
I'd experiment with https://vault.centos.org/7.9.2009/ but it seems this is x86_64-only, am I missing something?

**Review by xsuchy — APPROVED** [review]
+1

**Review by Conan-Kudo — CHANGES_REQUESTED** [review]
EPEL 7 is EOL too, so that needs to be handled.

**Comment by Conan-Kudo** [comment]
It would make sense to move all EL7 stuff to EOL now.

**Comment by nvkhoi112358** [comment]
I think Oracle Linux 7 (+ its EPEL) and RHEL 7 should be handled, too.

**Comment by praiskup** [comment]
Do we need to make it in one step?

**Comment by praiskup** [comment]
https://endoflife.date/oracle-linux seems to have a few more months 

I EOLed everything which is related to EPEL 7, though.  PTAL

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
