### PR TITLE
Better checking for qemu user static binaries

### PR DESCRIPTION
**Pull request by praiskup**
Relates:
https://bugzilla.redhat.com/show_bug.cgi?id=2143069
https://bodhi.fedoraproject.org/updates/FEDORA-2022-389622bd06

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@praiskup You might want to add `riscv64` as well, since we have that architecture being bootstrapped.

**Comment by praiskup** [comment]
Not sure how to test riscv64... we have no such configs yet.  I'd have to blindly add those. Therefore I'd probably let someone else to contribute this config change?

Anyway, when we merge this PR, even builds for riscv64 wouldn't be fatal...  mock will just warn and sleep(5).

**Comment by Conan-Kudo** [comment]
@davidlt has mock configs for Fedora RISC-V. The package name is `qemu-user-static-riscv` and the binary name is `qemu-riscv64-static`.

**Comment by praiskup** [comment]
I'm OK to review patch like that.  For now, I'm merging this PR

**Pull request merged**
