### PR TITLE
remove failovermethod=priority for dnf repos

### PR DESCRIPTION
**Pull request by istiak101**
Removed failovermethod=priority as this is removed from dnf lately.

### CODE REVIEW

**Comment by xsuchy** [comment]
I just checked and these lines are no longer neither in CentOS repo file nor in EPEL repo files. Therefore +1 from me.

**Review by xsuchy — APPROVED** [review]

**Comment by praiskup** [comment]
This wasn't to be merged, yet.  This is what is #752 about.  We still support el7, and the fork to mock-2 branch was not yet done.  Can we please keep the PRs open for at least 24 hours?  Thanks.

**Comment by Conan-Kudo** [comment]
> This wasn't to be merged, yet. This is what is #752 about. We still support el7, and the fork to mock-2 branch was not yet done. Can we please keep the PRs open for at least 24 hours? Thanks.

This wouldn't affect them anyway. By the time these configs are used, we switch over to target system DNF anyway.

**Comment by praiskup** [comment]
> to target system DNF

Or to target YUM.

**Comment by Conan-Kudo** [comment]
Nope, not with these configs. They're all set to use DNF. Not to mention, they'd _fail_ with YUM because of dependency errors.

**Comment by praiskup** [comment]
Ah, good point, el7 stays untouched.  DNF in EL7 is not something you consider people normally use, or?

**Comment by praiskup** [comment]
Can anyone face issues while installing bootstrap chroot using YUM, though?

**Comment by Conan-Kudo** [comment]
YUM bootstrap should already fail due to rich dependencies in EL8, DNF can handle them but RPM on EL7 can't.

**Comment by praiskup** [comment]
Not truth.  We use yum by default to install EL8 bootstrap with mock on EL7 system.  It just works.
Tested with `podman run --privileged --rm -ti centos:7 bash`

**Comment by Conan-Kudo** [comment]
Hmm, regardless, the failovermethod stuff should have no material impact. It only impacts how yum selects the next mirror when using mirrorlists to fail over to (as opposed to metalinks).

**Comment by istiak101** [comment]
I got multiple console warnings with epel-8-aarch64 & epel-8-x86_64 while building a package on mock 2.14 that's why I created this PR. Although upcoming dnf version will not throw any console output but on dnf.log as per this PR.

https://github.com/rpm-software-management/libdnf/pull/1276
https://bugzilla.redhat.com/show_bug.cgi?id=1961083

`Invalid configuration value: failovermethod=priority in /var/lib/mock/epel-8-aarch64/root/etc/dnf/dnf.conf; Configuration: OptionBinding with id "failovermethod" does not exist`

**Comment by praiskup** [comment]
Thanks for the info!

**Pull request merged**
