### PR TITLE
[CR-910] Discard unneccessary module_enable and module_install options for mock-core-configs

### PR DESCRIPTION
**Pull request by nkadel**
The documentation on using "modularity" for dnf is documented in docs/Feature-modularity.md  . The individual settings, commented out, are inconsistently listed and not in use.

### CODE REVIEW

**Comment by nkadel** [comment]
A separate pull request adding the commented out options consistently was rejected: let's clear these for consistency.

**Comment by Conan-Kudo** [comment]
What is CR-90?

**Comment by nkadel** [comment]
Should have been CF-190.

**Comment by Conan-Kudo** [comment]
What is that?

**Comment by praiskup** [comment]
@nkadel you mentioned this even in the commit message too:
> [CR-90] Discard unneccessary module_enable and module_install options… 

I can fix the style of the commit message myself, but I'm also not sure...
Do you mean this is related to #910 ?  If so, I'd prefer something like:
```
configs: drop comented-out modularity related options

This is documented in /usr/share/doc/mock/site-defaults.cfg and
in docs/Feature-modularity.md.

Relates: #910
```

**Comment by nkadel** [comment]
Feel free to tweak the comments. I admit that the "/etc/mock/site-defaults.cfg" having the same name as the deployed "/usr/share/doc/mock/site-defaults.cfg" has confused me before, but that's a very different issue.

**Pull request closed without merging**
