### PR TITLE
config: Fedora ELN fixes

### PR DESCRIPTION
**Pull request by praiskup**
This package doesn't appear to be available in ELN repos.

### CODE REVIEW

**Comment by praiskup** [comment]
@sgallagher can you PTAL?

**Comment by xsuchy** [comment]
So what's there? It was added there because several packages can satisfy the dependency and the other ones are huge.

**Comment by praiskup** [comment]
Seems like `glibc-all-langpacks` is installed (18M) as a dependency.

**Comment by xsuchy** [comment]
@sgallagher do you have any insight into why glibc-minimal-langpack is not present in the compose?

**Comment by sgallagher** [comment]
Yes, it's a bug that I'm working on, but I'm traveling for the remainder of the week, so I'll get to it on Monday.

**Comment by praiskup** [comment]
> Yes, it's a bug that I'm working on,

So I will drop the first patch, and we'll ship non-working ELN configs tomorrow.  The second patch
is still needed to make the non-composed i386 work.

**Pull request merged**
