### PR TITLE
mount /dev/loop-control and /dev/loopX into systemd-nspawn container

### LINKED ISSUE #298: /dev/loop-control and /dev/loop? not created in nspawn chroot
### Short description of the problem
/dev/loop-control and /dev/loop? device nodes are not created in the nspawn chroot, but they are in the classic chroot.

### Output of `rpm -q mock`
mock-1.4.16-2.fc30.noarch

### Steps to reproduce issue

1. mock -r fedora-rawhide-s390x --init
2. ll /dev/loop*

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

### PR DESCRIPTION
**Pull request by FrostyX**
Fix #298

### CODE REVIEW

**Comment by xsuchy** [comment]
```
mock shell --new-chroot
....
Start: shell
Failed to stat /dev/loop0: No such file or directory
Finish: shell
```

**Comment by FrostyX** [comment]
> Failed to stat /dev/loop0: No such file or directory

You don't have `/dev/loop0` on your host system or you do and there is some other issue? Should we check whether the loopX exists before mounting it?

**Comment by xsuchy** [comment]
On my host:
```
$ ls /dev/loop*
/dev/loop-control
```

**Comment by praiskup** [comment]
The same on my host.

**Comment by FrostyX** [comment]
On my host

    [jkadlcik@localhost mock]$ ls /dev/loop* -1
    /dev/loop0
    /dev/loop1
    /dev/loop10
    /dev/loop11
    /dev/loop2
    /dev/loop3
    /dev/loop4
    /dev/loop5
    /dev/loop6
    /dev/loop7
    /dev/loop8
    /dev/loop9
    /dev/loop-control

So, I've added a condition to mount those files only if they exist. Is it alright?

**Comment by FrostyX** [comment]
Canceling in favor of PR#430 by @praiskup

**Pull request closed without merging**
