### PR TITLE
Mark openSUSE Leap 15.0 as EOL and add openSUSE Leap 15.2

### LINKED ISSUE #530: opensuse-leap-15.0 configs don't work
```

 # /usr/bin/systemd-nspawn -q -M 2d80100ad39e443ea9278b954dfcbd4f -D /var/lib/mock/opensuse-leap-15.0-x86_64-bootstrap-39605-3059/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.aso_pfc2:/etc/resolv.conf --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/opensuse-leap-15.0-x86_64-39605-3059/rpmconfig --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 /usr/bin/dnf --installroot /var/lib/mock/opensuse-leap-15.0-x86_64-39605-3059/root/ --releasever 15.0 --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk install patterns-devel-base-devel_rpm_build --setopt=tsflags=nocontexts
DEBUG: Unsharing. Flags: 134217728
openSUSE Leap 15.0 - x86_64 - OSS                41 MB/s |  34 MB     00:00
openSUSE Leap 15.0 - x86_64 - Updates - OSS      37 MB/s |  77 MB     00:02
Last metadata expiration check: 0:00:10 ago on Wed Mar 11 07:51:55 2020.
Failed to set locale, defaulting to C
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 146, in resolving
    base.resolve(cli.demands.allow_erasing)
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 687, in resolve
    name=self.conf.protected_packages))
  File "/usr/lib/python3.6/site-packages/dnf/query.py", line 84, in filter
    return super(Query, self).filter(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/hawkey/__init__.py", line 392, in filter
    return new_query.filterm(*lst, **kwargs)
  File "/usr/lib64/python3.6/site-packages/hawkey/__init__.py", line 398, in filterm
    super(Query, self).filter(*arg_tuple)
TypeError: Expected a sequence.


real    1m22.446s
user    1m16.438s
sys     0m4.425s
FAILED: opensuse-leap-15.0-x86_64.cfg
```

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Fixes #530

### CODE REVIEW

**Comment by praiskup** [comment]
```
openSUSE Leap 15.2 - aarch64 - Updates - OSS                                                                                                                                                                 2.7 kB/s | 1.1 kB     00:00    
Errors during downloading metadata for repository 'updates-oss':
  - Status code: 404 for http://download.opensuse.org/ports/aarch64/update/leap/15.2/oss/repodata/repomd.xml.metalink (IP: 195.135.221.134)
Error: Failed to download metadata for repo 'updates-oss': Cannot prepare internal mirrorlist: Status code: 404 for http://download.opensuse.org/ports/aarch64/update/leap/15.2/oss/repodata/repomd.xml.metalink (IP: 195.135.221.134)
```

**Comment by Conan-Kudo** [comment]
Blech, looking into it...

**Comment by Conan-Kudo** [comment]
@praiskup Could you try now?

**Comment by praiskup** [comment]
Hmm, aarch is still weird:
```
ERROR: Command failed: 
 # /usr/bin/dnf --installroot /var/lib/mock/opensuse-leap-15.1-aarch64-bootstrap/root/ --releasever 15.1 --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk --forcearch aarch64 install dnf dnf-plugins-core --setopt=tsflags=nocontexts
No matches found for the following disable plugin patterns: local, spacewalk
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
openSUSE Leap 15.1 - aarch64 - OSS                                                                                                                                                                           3.9 MB/s |  36 MB     00:09    
openSUSE Leap 15.1 - aarch64 - Updates - OSS                                                                                                                                                                 3.7 MB/s |  67 MB     00:17    
Last metadata expiration check: 0:00:12 ago on Wed 11 Mar 2020 02:53:26 PM CET.
All matches were filtered out by exclude filtering for argument: dnf
All matches were filtered out by exclude filtering for argument: dnf-plugins-core
Error: Unable to find a match: dnf dnf-plugins-core
```

Neither 15.1 nor 15.2 works on my x86_64 with (automatic) --forcearch.

**Comment by praiskup** [comment]
Actually, even 15.2 with x86_64 has some repo problems:
```
openSUSE Leap 15.2 - x86_64 - Updates - OSS                                                                                                                                                                   11 kB/s | 5.8 kB     00:00    
Error: 
 Problem: package patterns-devel-base-devel_rpm_build-20170319-lp152.6.3.x86_64 requires netcfg, but none of the providers can be installed
  - conflicting requests
  - package netcfg-11.6-lp152.3.4.noarch is filtered out by exclude filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by Conan-Kudo** [comment]
@praiskup Whoops, I filtered out noarch packages. That should be fixed now!

**Comment by praiskup** [comment]
+1, thank you

**Pull request merged**
