### PR TITLE
Add Rocky Linux 9 Configuration and Modify Rocky Linux 8

### PR DESCRIPTION
**Pull request by nazunalika**
Hello. This PR does the following:

* Add Rocky Linux 9 configuration for all supported architectures
* Add Rocky Linux 9 as an alternative for EPEL 9 builds
* Refresh key name for Rocky Linux 8 for consistency

This PR depends on xsuchy/distribution-gpg-keys#67

### CODE REVIEW

**Comment by praiskup** [comment]
Thank you for the PR.

> This PR depends on https://github.com/xsuchy/distribution-gpg-keys/pull/67

Can you please bump the Requires: distribution-gpg-key version up to the to-be-released version?

**Comment by praiskup** [comment]
There seems to be some problem:
```
Errors during downloading metadata for repository 'baseos':
  - Status code: 404 for https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=BaseOS-9 (IP: 151.101.114.132)
```

**Comment by nazunalika** [comment]
Hello. As the current is version is 1.72, will setting it to 1.73 be sufficient?

And apologies on the 404. I should have clarified in both PR's our release time is around 14:00 UTC or so, so the 404's from mirror manager is expected. When we release, I can let notify you here on the PR.

**Comment by nazunalika** [comment]
Hello! I bumped the version as well as worked on the other PR based on some very helpful feedback. The mirror list should also be responding too. Again, apologies for the early 404's! Let me know if the currently enabled repos are reporting any further issues (baseos, appstream, crb, extras) or if you need anything else!

```
$ curl 'https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=BaseOS-9'
# repo = rocky-BaseOS-9.0 arch = x86_64 country = US country = global
https://dl.rockylinux.org/pub/rocky/9.0/BaseOS/x86_64/os/
https://rocky.deadbatteries.work/9.0/BaseOS/x86_64/os/
http://distro.ibiblio.org/rocky/9.0/BaseOS/x86_64/os/
http://mirror.anigil.com/rocky/9.0/BaseOS/x86_64/os/
http://mirror.nl.stackscale.com/rocky/9.0/BaseOS/x86_64/os/
```

**Comment by praiskup** [comment]
LGTM, thank you.

**Pull request closed without merging**
