### PR TITLE
Automatic commit of package [mock] release [5.4-1].

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by xsuchy** [comment]
I am oposed to use x.y.z  format. I vote for keeping x.y. I.e. use 5.4 for this release.

**Comment by praiskup** [comment]
Changed.

**Comment by xsuchy** [comment]
The commit description has not been changed.

**Comment by praiskup** [comment]
Good catch, fixed.

**Review by xsuchy — APPROVED** [review]
+1

**Pull request merged**
