### PR TITLE
Drop Fedora modular repositories from Fedora configs

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Fedora Modularity is no longer maintained.

### CODE REVIEW

**Review by keszybz — APPROVED** [review]

**Comment by praiskup** [comment]
Thank you, looks good, can you please add a short change-log entry?
https://rpm-software-management.github.io/mock/Release-Notes-New-Entry

**Comment by praiskup** [comment]
Ping on the PR.

**Comment by Conan-Kudo** [comment]
Yup, working on that now.

**Comment by Conan-Kudo** [comment]
Done.

**Review by praiskup — APPROVED** [review]
Thank you!

**Pull request merged**
