### PR TITLE
Automatic commit of package [mock] release [4.1-1].

### PR DESCRIPTION
**Pull request by praiskup**
Created by command:

/usr/bin/tito tag

### CODE REVIEW

**Comment by xsuchy** [comment]
Do not do this. When I rebase it, the tag gets broken. Push release notes separately. And tito tag push directly.

**Review by xsuchy — APPROVED** [review]

**Comment by praiskup** [comment]
The tag is not part of this PR;  I plan push the tag manually.

**Comment by praiskup** [comment]
Example commit from previous release: 38fabbbaf39544170cac14dfcacf825934649218

**Comment by praiskup** [comment]
Bumped the release date.

**Pull request merged**
