### PR TITLE
Fix 565

### PR DESCRIPTION
**Pull request by praiskup**
I'm not sure.  Don't we want to rather stop producing the list of installed
packages, as it is already printed out by dnf/yum?

### CODE REVIEW

**Comment by pmatilai** [comment]
Doh, didn't notice you already submitted a fix for this. Feel free to close #568 if you prefer doing it this way.

**Comment by praiskup** [comment]
Your fix seems slightly better ... do you think we need the output on mock's
output, though?

**Comment by pmatilai** [comment]
In the existing form, I don't know. What I'd find much more useful is the plain output of 'rpm -qa | sort' with the build dependencies installed in a separate file, so when "this was building fine just yesterday" happens, you could simply diff the files. As it is, the data is in the logs alright but getting it into a processable format requires quite a bit of sed-awk-wrestling.

**Comment by praiskup** [comment]
Merged #568.

**Pull request closed without merging**
