### PR TITLE
Add source repos to fedora-28-x86_64.cfg

### PR DESCRIPTION
**Pull request by sfowl**
This is just a small example to test if it would be acceptable to include source repos in mock configs.

This would allow for commands like, e.g.
```
$ mock -r fedora-28-x86_64 --dnf-cmd download -- --source vim
```
Note that the source repos have `enabled=0` so would not be checked by default.

If this is acceptable, I would be happy to make another PR that added source repos for all currently shipped fedora configs.

### CODE REVIEW

**Comment by xsuchy** [comment]
I struggle to find the use case here.  Why would you download sources to chroot?

**Comment by sfowl** [comment]
> I struggle to find the use case here. Why would you download sources to chroot?

To be clear, a package downloaded with `mock --dnf-cmd download` appears in the current working directory (i.e. not the chroot). I often need to download and repoquery srpms for inspection/testing.

Currently, I do this by manually updating the mock configs. `mock` has proven a very useful tool for switching between source repositories on a whim.

**Comment by xsuchy** [comment]
OK than. Feel free to add it to all config and I will merge it.

**Comment by sfowl** [comment]
Thanks, I've added source repos to all the fedora configs. 

It wasn't clear to me why some repos use `*-primary` gpgkeys and some used `*-secondary` gpgkeys, I tried to copy what was in the existing configs but this was done by hand so it's possible I made some mistakes.

**Comment by xsuchy** [comment]
Primary GPG key is used for primary arches and secondary for secondary arches. See https://fedoraproject.org/wiki/Architectures

**Comment by xsuchy** [comment]
Thank you.

**Pull request merged**
