### PR TITLE
add support for bsdtar

### PR DESCRIPTION
**Pull request by xsuchy**
Resolves: #169 

@praiskup @Conan-Kudo  what about this one?

### CODE REVIEW

**Comment by praiskup** [comment]
If you both (mock maintainer and OP) prefer this approach, why not.  `s/__cmd/__tar_cmd/` (nit).  I'd prefer one config option less, and slightly more consistent behavior across installations (plus I tend to prefer GNU tar usually).

**Comment by praiskup** [comment]
Oh, maybe combine it with #180; I mean `s/__cmd = "tar"/__cmd = "gtar"/`, and mock scm should be fixed too, there are other bsdtar incompatible options.

**Comment by Conan-Kudo** [comment]
I like this approach, and I agree with @praiskup that it should be combined with the other one so that we consistently call `gtar` vs `bsdtar`.

**Comment by xsuchy** [comment]
Updated.

**Comment by Conan-Kudo** [comment]
I agree with @praiskup. Looks good, but we should account for scm plugin. If you don't want to support `bsdtar` there, then just make sure it always calls `gtar`.

**Pull request merged**
