### PR TITLE
Add RHEL9 templates and configs

### PR DESCRIPTION
**Pull request by carlwgeorge**
Depends on https://github.com/xsuchy/distribution-gpg-keys/pull/63 to be merged first.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Why are you deleting the CentOS Stream+EPEL 9 config? We have those for EPEL 8, there's no reason not to have it for EPEL 9 too.

**Comment by Conan-Kudo** [comment]
The symlink files need to be dropped, so that we switch to the same system that exists for EPEL 8.

**Comment by carlwgeorge** [comment]
Dropped the symlinks and added the chroot aliases.

**Comment by praiskup** [comment]
Can you please bump the `Requires: distribution-gpg-keys` to  `>= 1.70 `?  Otherwise looks good.

**Comment by praiskup** [comment]
Thank you Carl and Neal!

**Pull request merged**
