### PR TITLE
Two fixes

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
cc @hroncok

**Comment by praiskup** [comment]
```
$ mock -r centos-stream-10-x86_64 --install       centos-release-virt-common
...
Dependencies resolved.
============================================================================================================================================================================================================================================
 Package                                                              Architecture                                     Version                                                Repository                                               Size
============================================================================================================================================================================================================================================
Installing:
 centos-release-virt-common                                           noarch                                           1-1.el10s                                              extras-common                                            15 k

Transaction Summary
============================================================================================================================================================================================================================================
Install  1 Package

Total download size: 15 k
Installed size: 19 k
Downloading Packages:
centos-release-virt-common-1-1.el10s.noarch.rpm                                                                                                                                                             111 kB/s |  15 kB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                        16 kB/s |  15 kB     00:00     
CentOS Stream 10 - Extras packages                                                                                                                                                                          1.6 MB/s | 1.6 kB     00:00    
GPG key at file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official-SHA256 (0x8483C65D) is already installed
The GPG keys listed for the "CentOS Stream 10 - Extras packages" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: centos-release-virt-common-1-1.el10s.noarch
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official-SHA256
Error: GPG check FAILED
```

Good catch.

**Comment by praiskup** [comment]
Please provide a release notes snippet, per the instructions
https://rpm-software-management.github.io/mock/Release-Notes-New-Entry

Id prefer to have everything in one commit.

**Review by praiskup — APPROVED** [review]
LGTM, thank you!

**Review by Conan-Kudo — APPROVED** [review]

**Comment by hroncok** [comment]
Thank you!

**Pull request merged**
