### PR TITLE
config: Add compatibility symlinks for EPEL 7 to centos+epel-7-* and mark aarch64/ppc64 as EOL arches

### PR DESCRIPTION
**Pull request by Conan-Kudo**

### CODE REVIEW

**Comment by praiskup** [comment]
Please remove the symlinks in the second commit, too.

**Comment by Conan-Kudo** [comment]
> Please remove the symlinks in the second commit, too.

Huh?

**Comment by praiskup** [comment]
> Huh?

Seems fixed now?

**Review by praiskup — APPROVED** [review]

**Comment by praiskup** [comment]
Merging a bit earlier, as I'd like to test this properly before release (ETA tomorrow).

**Pull request merged**
