### PR TITLE
Refresh openSUSE Leap mock configs

### PR DESCRIPTION
**Pull request by Conan-Kudo**
openSUSE Leap 15.3 is now EOL and openSUSE Leap 15.5 is the current version

### CODE REVIEW

**Comment by praiskup** [comment]
Could you please also move `templates/opensuse-leap-15.3.tpl` to `eol/templates/opensuse-leap-15.3.tpl` and ajust the `eol/opensuse-leap-15.3*` files accordingly?

**Comment by praiskup** [comment]
The new config seems to fail (buildroot installed by DNF from bootstrap):
```
...
Start: installing minimal buildroot with dnf
...

(208/208): glibc-locale-2.31-150300.52.2.x86_64.rpm                                                                                                                                                                                                                                                                                                                                                       1.6 MB/s |  12 MB     00:07    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                                                                                                                                                                                                     4.7 MB/s | 104 MB     00:22     
warning: Generating 18 missing index(es), please wait...
openSUSE Leap 15.5 - x86_64 - OSS                                                                                                                                                                                                                                                                                                                                                                         965 kB/s | 988  B     00:00    
Importing GPG key 0x3DBDC284:
 Userid     : "openSUSE Project Signing Key <opensuse@opensuse.org>"
 Fingerprint: 22C0 7BA5 3417 8CD0 2EFE 22AA B88B 2FD4 3DBD C284
 From       : /usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE
Key imported successfully
openSUSE Leap 15.5 - x86_64 - OSS                                                                                                                                                                                                                                                                                                                                                                         1.1 MB/s | 1.1 kB     00:00    
Importing GPG key 0x65176565:
 Userid     : "openSUSE:Backports OBS Project <openSUSE:Backports@build.opensuse.org>"
 Fingerprint: 637B 32FF 3D83 F07A 7AE1 C40A 9C21 4D40 6517 6565
 From       : /usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports
Key imported successfully
openSUSE Leap 15.5 - x86_64 - OSS                                                                                                                                                                                                                                                                                                                                                                         915 kB/s | 937  B     00:00    
Importing GPG key 0x39DB7C82:
 Userid     : "SuSE Package Signing Key <build@suse.de>"
 Fingerprint: FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82
 From       : /usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Key imported successfully
openSUSE Leap 15.5 - x86_64 - OSS - Updates                                                                                                                                                                                                                                                                                                                                                               965 kB/s | 988  B     00:00    
Importing GPG key 0x3DBDC284:
 Userid     : "openSUSE Project Signing Key <opensuse@opensuse.org>"
 Fingerprint: 22C0 7BA5 3417 8CD0 2EFE 22AA B88B 2FD4 3DBD C284
 From       : /usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for branding-openSUSE-15.5.20220322-lp155.3.7.noarch.rpm is not installed. Failing package is: branding-openSUSE-15.5.20220322-lp155.3.7.noarch
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Public key for openSUSE-release-15.5-lp155.286.1.x86_64.rpm is not installed. Failing package is: openSUSE-release-15.5-lp155.286.1.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Public key for openSUSE-release-ftp-15.5-lp155.286.1.x86_64.rpm is not installed. Failing package is: openSUSE-release-ftp-15.5-lp155.286.1.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Public key for patterns-base-base-20200505-lp155.10.5.x86_64.rpm is not installed. Failing package is: patterns-base-base-20200505-lp155.10.5.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Public key for patterns-base-basesystem-20200505-lp155.10.5.x86_64.rpm is not installed. Failing package is: patterns-base-basesystem-20200505-lp155.10.5.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Public key for patterns-base-minimal_base-20200505-lp155.10.5.x86_64.rpm is not installed. Failing package is: patterns-base-minimal_base-20200505-lp155.10.5.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Public key for patterns-devel-base-devel_rpm_build-20170319-lp155.2.4.x86_64.rpm is not installed. Failing package is: patterns-devel-base-devel_rpm_build-20170319-lp155.2.4.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Public key for systemd-presets-branding-openSUSE-12.2-lp155.4.5.noarch.rpm is not installed. Failing package is: systemd-presets-branding-openSUSE-12.2-lp155.4.5.noarch
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15
Public key for openSUSE-build-key-1.0-lp155.7.3.1.noarch.rpm is not installed. Failing package is: openSUSE-build-key-1.0-lp155.7.3.1.noarch
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE
Error: GPG check FAILED
WARNING: DNF command failed, retrying, attempt #2, sleeping 20s
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
```

**Comment by praiskup** [comment]
I'm not sure how to report the issue with signatures.  Does it make sense to merge this now when the config actually doesn't work?  Otherwise LGTM

**Comment by Conan-Kudo** [comment]
I need to check what's going on with the GPG keys then...

**Comment by praiskup** [comment]
Any progress here?  Note #1171, I'm thinking about "how to report such issues" or "whom to ask".

**Comment by Conan-Kudo** [comment]
Sorry, some IRL disruptions slowed things down. I'm going to look into this today.

**Comment by praiskup** [comment]
Gently ping on this, any progress?

**Comment by Conan-Kudo** [comment]
After talking to @lkocman, I need to get updated GPG public keys to include in distribution-gpg-keys. I'm checking with him on whether it's just openSUSE keys or if I also need SLE keys too.

**Comment by praiskup** [comment]
Ping again. We plan to release this week.

**Comment by Conan-Kudo** [comment]
PR for new keys to distribution-gpg-keys: https://github.com/xsuchy/distribution-gpg-keys/pull/103

This has been updated to use the new keys.

**Comment by Conan-Kudo** [comment]
@lkocman: to double check, are you sure we don't need both old and current openSUSE and SLE keys for this?

It seems distribution-gpg-keys has the "latest" openSUSE keys, so I'm confused why this is failing on the stuff using openSUSE-only keys...

**Comment by xsuchy** [comment]
Updated distribution-gpg-keys has been built in Fedora

**Comment by Conan-Kudo** [comment]
Blech, one more. https://github.com/xsuchy/distribution-gpg-keys/pull/104

**Comment by Conan-Kudo** [comment]
I'm double-checking the Backports key now too...

**Comment by Conan-Kudo** [comment]
I don't see any change to the Backports key, so I think this should work now.

**Review by praiskup — APPROVED** [review]
LGTM, thank you very much for taking care of this!

**Comment by praiskup** [comment]
Well actually:

```
/var/tmp/rpm-tmp.4qgv0n: line 1: /usr/sbin/sysusers2shadow: No such file or directory
error: %prein(system-group-hardware-20170617-150400.22.33.noarch) scriptlet failed, exit status 1

Error in PREIN scriptlet in rpm package system-group-hardware
  Running scriptlet: systemd-249.16-150400.8.33.1.x86_64                                                                                                                                                                            195/208 
error: system-group-hardware-20170617-150400.22.33.noarch: install failed
```

**Comment by praiskup** [comment]
I must be doing something wrong, after `--scrub=all` I see:
```
Importing GPG key 0x3FA1D6CE:
 Userid     : "SUSE Package Signing Key <build@suse.de>"
 Fingerprint: 7F00 9157 B127 B994 D5CF BE76 F74F 09BC 3FA1 D6CE
 From       : /usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-Main-2023
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for aaa_base-84.87+git20180409.04c9dae-150300.10.3.1.x86_64.rpm is not installed. Failing package is: aaa_base-84.87+git20180409.04c9dae-150300.10.3.1.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-2022, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-Main-2023
Public key for bash-4.4-150400.25.22.x86_64.rpm is not installed. Failing package is: bash-4.4-150400.25.22.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-2022, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-Main-2023
Public key for bash-sh-4.4-150400.25.22.x86_64.rpm is not installed. Failing package is: bash-sh-4.4-150400.25.22.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-2022, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-Main-2023
Public key for boost-license1_66_0-1.66.0-12.3.1.noarch.rpm is not installed. Failing package is: boost-license1_66_0-1.66.0-12.3.1.noarch
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-2022, file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports, file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-Main-2023
Public key for bzip2-1.0
```

(again installing buildroot using DNF from Suse installed in bootstrap)

**Review by praiskup — APPROVED** [review]
LGTM

**Pull request closed without merging**
